name: GH-200 CoHack
on: push
jobs:
  hello-world:
   runs-on: ubuntu-latest
   steps:
     - name: SayHello
       run: echo "Hello from GH-200 Cohack"
     - name: Copy code into runner
       uses: actions/checkout@v6
       
     - name: List file
       run: ls -la
     
    
  
